"""Test cases automatically generated by Pynguin (https://www.pynguin.eu)."""

import sys
import os
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

import pytest
import openunderstand.oudb.models as module_0
import peewee as module_1


def test_case_0():
    """Test KindModel creation."""
    kind_model_0 = module_0.KindModel()
    assert module_0.KindModel.is_ent_kind.default is True
    assert isinstance(module_0.KindModel.is_ref_kind, property)
    assert isinstance(module_0.KindModel.entities, module_1.BackrefAccessor)
    assert isinstance(module_0.KindModel.references, module_1.BackrefAccessor)


# Commented out - this test is flaky
# @pytest.mark.xfail(strict=True)
# def test_case_1():
#     reference_model_0 = module_0.ReferenceModel()
#     reference_model_0.__str__()


def test_case_2():
    """Test ProjectModel __str__ method."""
    project_model_0 = module_0.ProjectModel()
    assert module_0.ProjectModel.name.max_length == 128
    assert module_0.ProjectModel.language.max_length == 128
    assert module_0.ProjectModel.language.default == "Java"
    assert module_0.ProjectModel.root.max_length == 1024
    assert module_0.ProjectModel.db_path.max_length == 1024
    assert module_0.ProjectModel.db_path.unique is True
    var_0 = project_model_0.__str__()
    assert var_0 == "None"


def test_case_3():
    """Test ProjectModel __repr__ and __str__ methods."""
    project_model_0 = module_0.ProjectModel()
    assert module_0.ProjectModel.name.max_length == 128
    assert module_0.ProjectModel.language.max_length == 128
    assert module_0.ProjectModel.language.default == "Java"
    assert module_0.ProjectModel.root.max_length == 1024
    assert module_0.ProjectModel.db_path.max_length == 1024
    assert module_0.ProjectModel.db_path.unique is True
    var_0 = project_model_0.__repr__()
    assert var_0 == "None"
    var_1 = project_model_0.__str__()
    assert var_1 == "None"