# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import openunderstand.oudb.models as module_0
import peewee as module_1


def test_case_0():
    kind_model_0 = module_0.KindModel()
    assert module_0.KindModel.is_ent_kind.default is True
    assert isinstance(module_0.KindModel.is_ref_kind, property)
    assert isinstance(module_0.KindModel.entities, module_1.BackrefAccessor)
    assert isinstance(module_0.KindModel.references, module_1.BackrefAccessor)
    var_0 = kind_model_0.__str__()
    assert var_0 == "None"


def test_case_1():
    kind_model_0 = module_0.KindModel()
    assert module_0.KindModel.is_ent_kind.default is True
    assert isinstance(module_0.KindModel.is_ref_kind, property)
    assert isinstance(module_0.KindModel.entities, module_1.BackrefAccessor)
    assert isinstance(module_0.KindModel.references, module_1.BackrefAccessor)
    var_0 = kind_model_0.__repr__()
    assert var_0 == "None"


def test_case_2():
    kind_model_0 = module_0.KindModel()
    assert module_0.KindModel.is_ent_kind.default is True
    assert isinstance(module_0.KindModel.is_ref_kind, property)
    assert isinstance(module_0.KindModel.entities, module_1.BackrefAccessor)
    assert isinstance(module_0.KindModel.references, module_1.BackrefAccessor)


def test_case_3():
    entity_model_0 = module_0.EntityModel()
    assert isinstance(module_0.EntityModel.children, module_1.BackrefAccessor)
    assert isinstance(module_0.EntityModel.refs, module_1.BackrefAccessor)
    assert isinstance(module_0.EntityModel.inv_refs, module_1.BackrefAccessor)
    var_0 = entity_model_0.__repr__()
    assert var_0 == "None"


def test_case_4():
    """Test ReferenceModel __str__ method."""
    # Create a KindModel for the reference
    kind_model = module_0.KindModel()
    kind_model.is_ent_kind = False
    kind_model._name = "Test Reference"
    
    # Create entity models for file, ent, and scope
    entity_model = module_0.EntityModel()
    entity_model._name = "TestEntity"
    entity_model._longname = "TestEntity"
    
    # Create ReferenceModel with required foreign keys
    reference_model_0 = module_0.ReferenceModel()
    reference_model_0._kind = kind_model
    reference_model_0._file = entity_model
    reference_model_0._ent = entity_model
    reference_model_0._scope = entity_model
    reference_model_0._line = 10
    reference_model_0._column = 5
    
    # Now __str__ should work
    result = reference_model_0.__str__()
    assert isinstance(result, str)
    assert "Test Reference" in result
    assert "TestEntity" in result
    

def test_case_5():
    entity_model_0 = module_0.EntityModel()
    assert isinstance(module_0.EntityModel.children, module_1.BackrefAccessor)
    assert isinstance(module_0.EntityModel.refs, module_1.BackrefAccessor)
    assert isinstance(module_0.EntityModel.inv_refs, module_1.BackrefAccessor)
    var_0 = entity_model_0.__str__()
    assert var_0 == "None"
    var_1 = entity_model_0.__repr__()
    assert var_1 == "None"


def test_case_6():
    project_model_0 = module_0.ProjectModel()
    assert module_0.ProjectModel.name.max_length == 128
    assert module_0.ProjectModel.language.max_length == 128
    assert module_0.ProjectModel.language.default == "Java"
    assert module_0.ProjectModel.root.max_length == 1024
    assert module_0.ProjectModel.db_path.max_length == 1024
    assert module_0.ProjectModel.db_path.unique is True
    var_0 = project_model_0.__str__()
    assert var_0 == "None"


def test_case_7():
    project_model_0 = module_0.ProjectModel()
    assert module_0.ProjectModel.name.max_length == 128
    assert module_0.ProjectModel.language.max_length == 128
    assert module_0.ProjectModel.language.default == "Java"
    assert module_0.ProjectModel.root.max_length == 1024
    assert module_0.ProjectModel.db_path.max_length == 1024
    assert module_0.ProjectModel.db_path.unique is True
    var_0 = project_model_0.__repr__()
    assert var_0 == "None"
